name: Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, pdo_mysql
        coverage: xdebug

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --no-interaction

    - name: Copy .env
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Run database migrations
      run: php artisan migrate --force

    - name: Run tests
      run: php artisan test

          
    - name: Laravel Tests
  # You may pin to the exact commit or the version.
  # uses: hdev14/laravel-test-action@7dab92e8d7ae9f2c45c86f9061a4e8d0e80bb064
      uses: hdev14/laravel-test-action@v1
          

    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/var/www/laravel"

    # - name: SSH into server and check files
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.EC2_HOST }}
    #     username: ${{ secrets.EC2_USER }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     script: |
    #       composer install --no-dev && php artisan migrate --force && php artisan config:cache

    - name: Deploy Laravel on server
      uses: appleboy/ssh-action@master
       with:
       host: ${{ secrets.EC2_HOST }}
       username: ${{ secrets.EC2_USER }}
       key: ${{ secrets.SSH_PRIVATE_KEY }}
       script: |
      cd /var/www/laravel       # <- Laravel project folder
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
      php artisan config:cache
      php artisan route:cache
      sudo systemctl restart apache2

